<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    $checklist = [
        'Preparation' => [
            'Check Parking Brake is SET',
            'Request Ground Power via the EFB',
            'Request PLAN from Simbrief in EFB',
            'Battery ON',
            'Primary External Power ON',
            'Secondary External Power ON',
            'ADIRU ON',
            'FMC: Pos Init -> Drop Position IN',
            'FMC: Route Request',
            'FMC: Set Fuel',
            'FMC: Set Payload / Passengers',
            'FMC: Set Route -> LOAD -> Activate -> Execute',
            'Perf Init: Set ZFW -> Accept',
            'Wind: Legs -> RTE Data -> Load -> Execute',
            'FMC Comm -> DES Forecast -> Load -> Execute',
            'FMC: Set Departure and Arrival Runways / SIDs / STARs',
            'Check Flight Route',
            'IFE / Pass Seats ON',
            'Cabin / Utility ON',
            'Emergency Lights ON',
            'Window Heat ON',
            'Hydraulic: Bottom Right Pump ON (brakes)',
            'MCP: Flight Director ON',
            'MCP: Heading to Runway',
            'MCP: Set Cleared Altitude',
            'Autobrake RTO',
            'Set QNH',
            'EFB: Performance Tool for Take Off',
            'INIT REF: Flaps X',
            'INIT REF: Set CG, Thrust Temp and V-Speeds',
            'Set Trim',
            'APU: ON, wait 3s then START',
            'Primary External Power OFF',
            'Secondary External Power OFF',
            'EFB: Release Power and Services',
            'EFB: Remove Chocks',
            'Hydraulics: C2 / C1 ON',
            'Hydraulics: Bottom Left Demand AUTO',
            'Hydraulics: C1 Air / C2 Air AUTO',
            'Fuel Pumps ON (long x6) (short x4)',
            'Seatbelts ON',
            'Beacon ON',
            'Onboard Checklists',
            'Release Brakes',
            'Pushback',
            'Set Parking Brake',
            'Engine 1: Start',
            'Engine 1: Fuel Lever ON',
            'Engine 2: Start',
            'Engine 2: Fuel Lever ON',
            'Set Flaps',
            'APU: OFF',
            'Taxi Lights ON',
            'Taxi to Runway',
            'Recall',
            'Start Clock',
        ],
        'Start Taxi' => [
            'MCP: Set Speed V2',
            'MCP: LNAV ON',
            'MCP: VNAV ON',
            'Set Squak 2000 and XPDR',
            'Transponder TA/RA',
        ],
        'Lights' => [
            'Landing Lights ON',
            'Runway Turnoffs ON',
            'Strobes ON',
            'Wing Lights ON',
            'Check OTHER Lights',
        ],
        'Take Off' => [
            'Gear Up',
            'Flaps UP',
            'AP ON',
        ],
        'Climb' => [
            'Taxi OFF',
            'Switch to STD at Transition 6k (UK) 18k (US) 5k (Germany) 7k (Turkey)',
            '10k Landing Lights OFF',
        ],
        'Cruise' => [
            'Auto Brakes OFF (FROM RTO)',
            'Seatbelts OFF',
            'Set approach reference in FMC (flaps 30)',
        ],
        'Descent' => [
            'Set the cleared LOW altitude before TOD reached',
            'Speed brakes when needed',
            'Arm Speedbrake',
            'Autobrake ON',
            'Seatbelts ON',
            'Checklists',
            'Landing Lights ON (10k)',
            'Taxi lights ON (5k)',
            'Check QNH / Switch OFF STD',
        ],
        'Landing' => [
            'Gear Down',
            'Flaps 30',
            'Approach mode when lined up',
        ],
        'Post Flight' => [
            'Landing Lights OFF',
            'Flaps UP',
            'Spoilers NONE',
        ],
        'Power Down' => [
            'Taxi lights OFF',
            'Chocks on in FMC',
            'Seatbelts OFF',
            'Engines Off With Levers 1 and 2',
            'Clean up Overhead Panel',
            'Ground Power OFF',
            'Battery OFF',
        ],
    ];

    return view('checklist', [
        'checklist' => $checklist,
    ]);
});
