<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {

    $checklist = [
        'Preparation' => [
            'Check Parking Brake is SET',
            'Request Ground Power via the FMC',
            'Request PLAN from Simbrief in EFB',
            'Battery ON',
            'Transfer to Ground Power',
            'Turn on Inertial Navigation System (IRS)',
            'Emergency Lights ARMED and CLOSE lid',
            'Window Heaters ON',
            'Set FUEL from the FMC (Block Fuel)',
            'Set PAYLOAD / PASSENGERS from the FMC',
            'Setup the FMC with the FLIGHT PLAN, ROUTE, SIDs, STARs',
            'Check ALL LEGS in the plan have valid altitude and speed restrictions',
            'Set the trim wheel',
            'Turn on the FD x 2 (Flight Directors)',
            'Set Heading to Runway (Navigraph Charts)',
            'Enable Lateral Navigation (LNAV)',
            'Set BARO pressure (B)',
            'Seatbelts ON',
            'Beep and Bloops ON',
            'Yaw Dampers ON',
            'AFT Fuel Pump ON',
            'APU Start',
            'Wait for APU to SETTLE',
            'Transfer POWER to APU x2 (Inner Switches)',
            'Disconnect Ground Power',
            'Remove Chocks',
            'Set ALTITUDE to MAX cleared level',
            'Set AUTO Brake to RTO (Rejected Take Off)',
            'Anti Collision Lights ON',
            'Check Parking Brake is SET',
            '(6) Turn ON the remaining 3 Fuel Pumps',
            '(6) Turn ON the APU Bleed ready to turn the engine with compressed air',
            'Start Pushback',
            'Check Parking is NOT SET',
            'Engine 2 Start - Dial to GROUND',
            'Flick Ignition Switch (Any)',
            'Number 2 Starter Lever ON',
            'Engine 1 Start - Dial to GROUND',
            'Flick Ignition Switch (Any)',
            'Number 1 Starter Lever ON (Near all Levers)',
            'Central Fuel Pumps ON (Central Tanks Have Fuel?)',
            'Switch Power from APU to ENGINES (Two Outer Switches Down)',
            'APU OFF',
            'APU Bleed OFF',
            'Hydraulic Pumps ON',
            'Packs ON (Both LEFT and RIGHT)',
            'Set Pressurisation to cruise altitude',
            'Landing ALT set to airport elevation',
            'Taxi ON',
            'FLAPS to 5',
        ],
        'Start Taxi' => [
            'Set MCP Speed to match V2 Speed',
            'Probe Heaters / Pitot ON (x2)',
            'Arm the Autothrottle',
            'Arm LNAV and VNAV',
            'Disable VNAV',
            'Transponder TCAS mode to TA/RA',
            'Set squawk to 2200 (Traffic Advisory / Resolution Advisory)',
        ],
        'Lights' => [
            'Strobes ON (up)',
            'Landing Lights ON',
            'Check OTHER Lights',
        ],
        'Take Off' => [
            'Take Off',
            'Gear Up',
            'AP ON',
            'VNAV ON',
            'Depressurise Gear',
            'Taxi OFF',
            'Flaps UP',
            'Check Autothrottle',
            'Check LNAV / VNAV Again',
            'Switch to STD at Transition 6k (UK) 18k (US) 5k (Germany) 7k (Turkey)',
            '10k Landing Lights OFF',
        ],
        'Cruise' => [
            'Auto Brakes OFF (FROM RTO)',
            'Seatbelts OFF',
            'The ILS information we have selected is available on the INIT REF page',
            'Set ILS Radios (BOTH)',
            'Set BOTH course knobs to the DESTINATION runway',
            'Set approach reference in FMC (flaps 30)',
            'Set wind speeds in forecast (DES Page)',
        ],
        'Descent' => [
            'Look for the TOD (Top of Descent)',
            'Set the cleared LOW altitude before TOD reached',
            'Speed brakes when needed',
            '10k Landing Lights ON',
            'Check QNH / Switch OFF STD',
        ],
        'Landing' => [
            'Autobrake ON',
            'Seatbelts ON',
            'Gear Down',
            'Approach mode when lined up',
            'Both APs ON',
            'Taxi lights ON',
            'Flaps 30',
        ],
        'Post Flight' => [
            'Landing Light OFF',
            'Flaps UP',
            'Spoilers NONE',
        ],
        'Power Down' => [
            'Taxi lights OFF',
            'Chocks on in FMC',
            'Request Ground Power',
            'Switch to Ground Power',
            'Seatbelts OFF',
            'Engines Off With Levers 1 and 2',
            'Clean up Overhead Panel',
            'Clean up IRS',
            'Ground Power OFF',
            'Battery OFF',
        ],
    ];

    return view('checklist', [
        'checklist' => $checklist,
    ]);
});
